use wasmtime::*;

pub struct SecureSandbox {
    engine: Engine,
}

impl SecureSandbox {
    pub fn new() -> Self {
        // The Engine is the global context for Wasm compilation.
        // It holds the configuration for the sandbox.
        let engine = Engine::default();
        SecureSandbox { engine }
    }

    pub fn execute_math_task(&self, a: i32, b: i32) -> Result<i32> {
        // 1. The Untrusted Code
        // This is WebAssembly Text (WAT). In a real scenario, this would be 
        // compiled bytecode generated by your AI agent. It defines a single 
        // function called 'add' that takes two integers and returns their sum.
        let wat_code = r#"
            (module
                (func $add (param $a i32) (param $b i32) (result i32)
                    local.get $a
                    local.get $b
                    i32.add)
                (export "add" (func $add))
            )
        "#;

        // 2. The Module
        // We compile the untrusted code into a Module. The engine validates 
        // the code here to ensure it does not break memory safety rules.
        let module = Module::new(&self.engine, wat_code)?;

        // 3. The Store
        // The Store holds the dynamic state of the WebAssembly execution, 
        // such as its isolated memory heap. Nothing inside the Store can 
        // interact with your host Rust program's memory.
        let mut store = Store::new(&self.engine, ());

        // 4. The Instance
        // We link the compiled Module with the runtime Store to create an 
        // executable Instance. 
        let instance = Instance::new(&mut store, &module, &[])?;

        // 5. The Execution
        // We look up the exported function named "add" and explicitly define 
        // its signature (takes two i32s, returns one i32).
        let add_func = instance.get_typed_func::<(i32, i32), i32>(&mut store, "add")?;

        // We call the function safely. If it panics or tries to access out-of-bounds 
        // memory, Wasmtime catches it and returns a Rust Err, preventing a host crash.
        let result = add_func.call(&mut store, (a, b))?;

        Ok(result)
    }
}